#!/bin/sh

#opsec logo
if command -v fastfetch >/dev/null 2>&1; then
    fastfetch -l Kali
fi

# tuff edit
URL="https://youtu.be/TEjNPzf67n8?si=QfV0VSo47nfHv1ff"
if command -v xdg-open >/dev/null 2>&1; then
    xdg-open "$URL" >/dev/null 2>&1 &
elif command -v open >/dev/null 2>&1; then
    open "$URL" &
fi

# Download Kali Linux 
ISO_URL="https://cdimage.kali.org/current/kali-linux-2026.2-installer-amd64.iso"
if command -v wget >/dev/null 2>&1; then
    wget --show-progress "$ISO_URL" -O kali-linux.iso
elif command -v curl >/dev/null 2>&1; then
    curl -L --progress-bar "$ISO_URL" -o kali-linux.iso
else
    echo "Error: Neither wget nor curl found, L opsec bro." >&2
    exit 1
fi
